version: "3.8"
services:
  redis:
    image: redis:latest
    hostname: redis
    container_name: redis
    ports:
      - 8601:6379
    networks:
      - makala_network
  redis-commander:
    image: rediscommander/redis-commander:latest
    hostname: redis-commander
    links:
      - redis
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8602:8081
    networks:
      - makala_network
  postgres:
    restart: always
    image: postgres:11
    hostname: postgres
    container_name: postgres
    environment:
      - "POSTGRES_DB=simple"
      - "POSTGRES_USER=simple"
      - "POSTGRES_PASSWORD=simple"
      - "TZ=Asia/Almaty"
    ports:
      - 8603:5432
    networks:
      - makala_network

networks:
  makala_network:
    driver: bridge
