// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package poststore

import (
	"context"
)

type Querier interface {
	// stores post in database (without any further operation on the post)
	Create(ctx context.Context, arg CreateParams) (FeedPost, error)
	// fetches all posts ordered by their id
	GetAll(ctx context.Context, arg GetAllParams) ([]FeedPost, error)
	// fetches posts by ids
	GetByIds(ctx context.Context, dollar_1 []int64) ([]FeedPost, error)
}

var _ Querier = (*Queries)(nil)
